#! /bin/sh

#                      _     _                              _
#                     / \   | | _   _   ___  __ _  _ __  __| |
#                    / _ \  | || | | | / __|/ _` || '__|/ _` |
#                   / ___ \ | || |_| || (__| (_| || |  | (_| |
#                  /_/   \_\|_| \__,_| \___|\__,_||_|   \__,_|

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d " പണി" " പഠനം" " സിനിമ" " സംഗീതം" " മെസേജിംഗ്" "6" "7" "8" "9" " ഈമാക്സ്"

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

$HOME/.config/polybar/launch
feh --bg-fill --randomize Pictures/Wallpapers
bspc rule -a Emacs desktop=^0


pgrep -x emacs > /dev/null || emacs &
pgrep -x picom > /dev/null || picom --config ~/.config/picom/picom.conf  --inactive-dim 0.7 &
